### PR TITLE
Single File Component

### PR DESCRIPTION
**Pull request by KABBOUCHI**
Implements #4

## Features:

- Transform Vue SFC (hook)
- Change folder structure.

## Bugs: 

- Hook not always executing (manually => node hooks/before-prepare/nativescript-dev-android-snapshot.js)
- Lost two-way binding( only working from JS to DOM)

## Screenshots:

image
image
image
image
image

### CODE REVIEW

**Comment by rigor789** [comment]
Hey @KABBOUCHI. Thanks for submitting this PR!

There has been an effort by @tralves to bring `.vue` file support to NativeScript (https://github.com/tralves/nativescript-vue-webpack-template) using webpack and vue-loader.

And I think I'd like to keep the `.vue` file support out of this repository.

Do you think your changes could work as a nativescript template or a plugin?

Awesome that you got the `<style>` tags working, and I think extracting to a css file is the right way to go.

I haven't seen browserify used too much lately, is `vueify` still supported (last activity mar 9)?
I'm thinking, since webpack is the officially supported "bundler" both for NativeScript and Vue, we should work on having the webpack template fully functional instead of browserify. 

Since you got the `<style>` tags working, could you look at https://github.com/tralves/nativescript-vue-webpack-template/issues/1 ?

**Comment by tralves** [comment]
Nice work!

I am on vacations and so I can't test it now. I agree with @rigor789 in
that we should let the webpack plugins do the work to bundle the single
file components because that way we use the "official" Vue tools instead of
maintaining scripts to do the same thing. There may be other stuff that
`vue-loader` does that we don't know too.

For instance, will `<styles lang="scss" scoped>` work?

In any case, impressive work!

**Comment by KABBOUCHI** [comment]
@rigor789  I was hoping you split the sample to another repo(template). 

I can't create a nativescript template, I don't have much experience with nativescript.

I'll check @tralves template repo in the weekend.

**Comment by rigor789** [comment]
@KABBOUCHI the samples will be kept in this repo, as they are mainly used during development to test out new changes, and having them in the same repo makes this easier.

That's fine, there is probably no need to create a new template, instead we should work on the one by @tralves and make that "the template". If you have some time, you could move your changes regarding the `<style>` tags into the template repo, since that is the only feature currently missing.

**Comment by KABBOUCHI** [comment]
@rigor789  @tralves  https://github.com/tralves/nativescript-vue-webpack-template/pull/3

It was an easy fix. 

I think the main problem in this template is the live update, not the style.

**Comment by rigor789** [comment]
This has been now implemented in https://github.com/tralves/nativescript-vue-webpack-template

Closing.

**Pull request closed without merging**
