### PR TITLE
Fix iOS crash on startup (b.prototype blah blah)

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hi,

Moving the require of `application` to the top fixes the crash on iOS.

Keep up the great work!
Eddy

### CODE REVIEW

**Comment by jlooper** [comment]
w00t!

**Comment by jlooper** [comment]
I see that the list-view template doesn't seem to run as well on iOS, although it does start up now; when tapping on a list item, the app crashes - a problem with routing on iOS?

**Comment by rigor789** [comment]
Is that the example code from the repo, or is it different? Is is the same error as before?

**Comment by EddyVerbruggen** [comment]
@rigor789 Indeed it's the same error and it crashes on the `app-with-list-view.js` sample indeed.

**Pull request merged**
