### PR TITLE
Change in folder structure

### PR DESCRIPTION
**Pull request by tralves**
This PR has lots of changes, but is just a change in the folder structure.

## Problem
Currently, if we clone the repository or install the dependency from the repository, the path to the compiled dist file will be `nativescript-vue/nativescript-vue/dist/index.js`, which feels weird. The `npm link` trick would solve some cases, but I ran into some issues when using webpack. 

## Changes
- Everything under `nativescript-vue` is now in the root of the package. 
- Renamed `vue-sample` to `samples`.
- Updated samples do they still work in the new structure.
- Updated .gitignore and other configuration files to match this new structure.

What do you think?

### CODE REVIEW

**Comment by rigor789** [comment]
Does this simplify the development process by not having to run `npm-link`? (For the samples I mean) 

I guess we can do this, easier to work on by not having to go into directories all the time!

Also I was thinking if we should start publishing to npm.

**Comment by tralves** [comment]
It does avoid avoid having to do `npm link`. In fact, I made this change also because webpack does not resolve dependencies of linked modules (not without some extra work). The samples are working without `npm link` too.

I think it also helps when developing with another project. For instance, in the [template I created](https://github.com/tralves/nativescript-vue-webpack-template), I just added the `nativescript-vue` dependency directly from my github fork like this:
```
"dependencies": {
  "nativescript-vue": "tralves/nativescript-vue",
```
and then import the lib with `const Vue = require('nativescript-vue/dist/index')`. With the current folder structure, this line would be `const Vue = require('nativescript-vue/nativescript-vue/dist/index')` which feels weird to me.

Even without these "practical" reasons, I think it is a better structure, more in line with what we see libs do around the world.

**Comment by gvsrepins** [comment]
+1. It makes sense to me.

> Also I was thinking if we should start publishing to npm.

Agreed. It looks like that this change will also facilitate the npm publishing process.

**Comment by vesper8** [comment]
I don't know whether my problems were related to the installation instructions that need to be updated, or an unforeseen problem. But I can tell after reading this that my issue and this PR are very much related

https://github.com/rigor789/nativescript-vue/issues/27

**Pull request merged**
